env:
  run_bioccheck: 'false'
  has_testthat: 'true'
  run_covr: 'true'
  run_pkgdown: 'true'
  has_RUnit: 'false'
  cache-version: 'cache-v1' 
  run_docker: 'false'

jobs:
  build:
  uses:
    neurogenomics/r_workflows/.github/workflows/check-bioc-docker.yml